### ISSUE TITLE
uncaught exception

### ISSUE THREAD

**Issue by remicollet** [llaville/php-compat-info#303]
```
$ phpcompatinfo reference:show mongodb

Fatal error: Uncaught Error: Call to a member function getReleases() on null in /usr/share/php/Bartlett/CompatInfo/Api/V5/Reference.php:143
Stack trace:
#0 [internal function]: Bartlett\CompatInfo\Api\V5\Reference->show('mongodb', Object(Closure), false, false, false, false, false, false, false, false, Object(Bartlett\CompatInfoDb\Application\Query\Show\ShowHandler))
#1 /usr/share/php/Bartlett/Reflect/Client/LocalClient.php(87): call_user_func_array(Array, Array)
#2 /usr/share/php/Bartlett/Reflect/Api/BaseApi.php(73): Bartlett\Reflect\Client\LocalClient->request('POST', 'reference/show', Array)
#3 /usr/share/php/Bartlett/CompatInfo/Api/Reference.php(102): Bartlett\Reflect\Api\BaseApi->request('reference/show', 'POST', Array)
#4 [internal function]: Bartlett\CompatInfo\Api\Reference->show('mongodb', false, false, false, false, false, false, false, false, false, Object(Bartlett\CompatInfoDb\Application\Query\Show\ShowHandler))
#5 /usr/share/php/Bartlett/CompatInfo/Console/CommandFactory.php(335): call_user_func_array(Array, in /usr/share/php/Bartlett/CompatInfo/Api/V5/Reference.php on line 143

```

Of course **mongodb**  is not known, but this should probably be reported more clearly.

**Comment by llaville** [comment]
Only affect versions 5.5.x (not 6.0.x-dev).
Fixe only available on branch 5.5, in waiting future bugfix release !
